server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MBDS-ANTENNES-24-25/projet-not-spring-microservices-JedidiahRC
          clone-on-start: true
          search-paths: '{application}'

management:
  endpoints:
    web:
      exposure:
        include: "*"