server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:postedb
  h2:
    console:
      enabled: true
      path: /h2-console

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka

resilience4j:
  circuitbreaker:
    instances:
      competenceService:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
  timelimiter:
    instances:
      competenceService:
        timeoutDuration: 3s